<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Session_Guard {
    public static function register_hooks(){add_filter('login_redirect',array(__CLASS__,'login_redirect'),20,3);add_action('init',array(__CLASS__,'enforce_primary'),1);add_action('login_form',array(__CLASS__,'render_oauth_login'));add_action('login_init',array(__CLASS__,'handle_login_actions'));add_action('admin_post_kornsw_ath_admin_bypass',array(__CLASS__,'admin_bypass'));}
    public static function login_redirect($redirect_to,$requested,$user){if(!($user instanceof WP_User))return $redirect_to;$primary=KornSW_ATH_Config_Repository::get_primary_source_uid();if($primary==='')return $redirect_to;$profile=KornSW_ATH_Config_Repository::get_profile($primary);$mode=(string)(($profile['AuthTokenConfig']??array())['IssueMode']??'');if(!str_starts_with($mode,'OAUTH_'))return $requested?:$redirect_to;if(in_array('administrator',(array)$user->roles,true))return self::choice_url($requested?:$redirect_to);return admin_url('admin-post.php?action=kornsw_ath_oauth_start&source='.rawurlencode($primary).'&purpose=primary&return='.rawurlencode($requested?:$redirect_to));}
    private static function choice_url($return){return add_query_arg(array('action'=>'kornsw_ath_admin_choice','return'=>$return),wp_login_url());}
    public static function handle_login_actions(){if(($_REQUEST['action']??'')==='kornsw_ath_oauth_login'){$primary=KornSW_ATH_Config_Repository::get_primary_source_uid();if($primary==='')wp_die('Keine Primary Token Source konfiguriert.');$return=esc_url_raw(wp_unslash($_REQUEST['redirect_to']??admin_url()));KornSW_ATH_OAuth_Flow::start($primary,$return,'primary');}if(($_REQUEST['action']??'')==='kornsw_ath_admin_choice')self::render_admin_choice();}
    private static function render_admin_choice(){if(!is_user_logged_in())auth_redirect();$user=wp_get_current_user();if(!in_array('administrator',(array)$user->roles,true))wp_die('Nicht erlaubt.',403);$primary=KornSW_ATH_Config_Repository::get_primary_source_uid();$return=esc_url_raw(wp_unslash($_GET['return']??admin_url()));?><!doctype html><html><head><meta charset="utf-8"><title>Authentifizierung wählen</title><?php wp_admin_css('login',true); ?></head><body class="login"><div id="login"><h1><a href="<?php echo esc_url(home_url('/')); ?>">WordPress</a></h1><div class="message"><p>Für Administratoren bleibt ein lokaler Notfallzugang erhalten. Möchtest du die primäre Token Source verwenden oder diese Pflicht nur für die aktuelle WordPress-Sitzung deaktivieren?</p></div><p><a class="button button-primary button-large" style="width:100%;text-align:center" href="<?php echo esc_url(admin_url('admin-post.php?action=kornsw_ath_oauth_start&source='.rawurlencode($primary).'&purpose=primary&return='.rawurlencode($return))); ?>">Mit OAuth fortfahren</a></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="kornsw_ath_admin_bypass"><input type="hidden" name="return" value="<?php echo esc_attr($return); ?>"><?php wp_nonce_field('kornsw_ath_admin_bypass'); ?><p><button class="button button-secondary button-large" style="width:100%">Nur WordPress-Passwort für diese Sitzung</button></p></form></div></body></html><?php exit;}
    public static function admin_bypass(){check_admin_referer('kornsw_ath_admin_bypass');$user=wp_get_current_user();if(!$user->ID||!in_array('administrator',(array)$user->roles,true))wp_die('Nicht erlaubt.',403);KornSW_ATH_Storage::set_binding($user->ID,'',true);wp_safe_redirect(wp_unslash($_POST['return']??admin_url()));exit;}
    public static function enforce_primary(){if(!is_user_logged_in())return;$primary=KornSW_ATH_Config_Repository::get_primary_source_uid();if($primary==='')return;if(self::is_own_flow())return;$user=wp_get_current_user();$binding=KornSW_ATH_Storage::get_binding($user->ID);if($binding&&!empty($binding['bypass_primary'])&&in_array('administrator',(array)$user->roles,true))return;if(!$binding||$binding['source_uid']!==$primary){$probe=KornSW_ATH_Token_Manager::try_get_access_token($primary,$user->ID);if(($probe['status']??'')==='SUCCESS'){KornSW_ATH_Storage::set_binding($user->ID,$primary,false);return;}if(KornSW_ATH_OAuth_Flow::is_interactive_request()){$return=KornSW_ATH_OAuth_Flow::current_url();if(in_array('administrator',(array)$user->roles,true)){wp_safe_redirect(self::choice_url($return));exit;}KornSW_ATH_OAuth_Flow::start($primary,$return,'primary');}self::terminate_current_session('Primary token binding missing.');}
        $r=KornSW_ATH_Token_Manager::try_get_access_token($primary,$user->ID);if($r['status']==='SUCCESS')return;self::terminate_current_session('Primary token validation failed: '.$r['status']);}
    private static function terminate_current_session($reason){$user_id=get_current_user_id();$token=wp_get_session_token();if($user_id&&$token!=='')WP_Session_Tokens::get_instance($user_id)->destroy($token);wp_clear_auth_cookie();do_action('kornsw_authtokenhandling_primary_session_terminated',$user_id,$reason);if(KornSW_ATH_OAuth_Flow::is_interactive_request()){wp_safe_redirect(wp_login_url(KornSW_ATH_OAuth_Flow::current_url()));exit;}wp_die('Authentication required.',401);}
    private static function is_own_flow(){$action=sanitize_key(wp_unslash($_REQUEST['action']??''));return str_starts_with($action,'kornsw_ath_');}
    public static function render_oauth_login(){$primary=KornSW_ATH_Config_Repository::get_primary_source_uid();if($primary==='')return;$profile=KornSW_ATH_Config_Repository::get_profile($primary);if(!$profile)return;$mode=(string)(($profile['AuthTokenConfig']??array())['IssueMode']??'');if(!str_starts_with($mode,'OAUTH_'))return;$return=esc_url_raw(wp_unslash($_REQUEST['redirect_to']??admin_url()));$label=esc_html($profile['DisplayName']??'OAuth');echo '<p style="margin-top:16px"><a class="button button-secondary button-large" style="width:100%;text-align:center" href="'.esc_url(add_query_arg(array('action'=>'kornsw_ath_oauth_login','redirect_to'=>$return),wp_login_url())).'">Mit '. $label .' anmelden</a></p>';}
}
