<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_OAuth_Server_Admin {
    public static function register_hooks(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_post_kornsw_ath_save_oauth_server',array(__CLASS__,'save'));}
    public static function menu(){add_users_page('OAuthServer (KornSW)','OAuthServer (KornSW)','manage_options','kornsw-oauthserver',array(__CLASS__,'page'));}
    public static function save(){if(!current_user_can('manage_options'))wp_die('Nicht erlaubt.',403);check_admin_referer('kornsw_ath_save_oauth_server');KornSW_ATH_OAuth_Server_Config::save($_POST);wp_safe_redirect(add_query_arg(array('page'=>'kornsw-oauthserver','updated'=>'true'),admin_url('users.php')));exit;}
    public static function page(){if(!current_user_can('manage_options'))return;$clients=KornSW_ATH_OAuth_Server_Config::clients();$role_scopes=KornSW_ATH_OAuth_Server_Config::role_scopes();$user_scopes=KornSW_ATH_OAuth_Server_Config::user_scopes();global $wp_roles; ?>
<div class="wrap"><h1>OAuthServer (KornSW)</h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="kornsw_ath_save_oauth_server"><?php wp_nonce_field('kornsw_ath_save_oauth_server'); ?>
<p><label><input type="checkbox" name="server_enabled" value="1" <?php checked(KornSW_ATH_OAuth_Server_Config::enabled()); ?>> <strong>OAuth-Server-Modus aktivieren</strong></label></p>
<h2>Endpunkte</h2><table class="widefat striped"><tbody><tr><td>Authorization</td><td><code><?php echo esc_html(KornSW_ATH_OAuth_Server_Config::authorize_endpoint()); ?></code></td></tr><tr><td>Token</td><td><code><?php echo esc_html(KornSW_ATH_OAuth_Server_Config::token_endpoint()); ?></code></td></tr><tr><td>Introspection</td><td><code><?php echo esc_html(KornSW_ATH_OAuth_Server_Config::introspection_endpoint()); ?></code></td></tr><tr><td>Issuer</td><td><code><?php echo esc_html(KornSW_ATH_OAuth_Server_Config::issuer()); ?></code></td></tr></tbody></table>
<h2>OAuth Clients</h2><p class="description">RedirectUri darf <code>*</code> in Pfad/Query enthalten. Scheme und Host dürfen niemals Wildcards enthalten.</p><table class="widefat striped" id="ath-server-clients"><thead><tr><th>Titel</th><th>ClientId</th><th>ClientSecret</th><th>RedirectUri / Maske</th><th></th></tr></thead><tbody><?php foreach($clients as $c)self::client_row($c); ?></tbody></table><p><button type="button" class="button" id="ath-add-server-client">Client hinzufügen</button></p>
<h2>Scopes je Benutzerrolle</h2><p class="description">Die Rolle selbst wird zusätzlich automatisch als <code>Role:&lt;Rolle&gt;</code> geliefert. Weitere Einträge sind leerzeichengetrennt.</p><table class="widefat striped"><tbody><?php foreach($wp_roles->roles as $slug=>$role){ ?><tr><th style="width:220px"><?php echo esc_html($role['name']); ?> <code><?php echo esc_html($slug); ?></code></th><td><input class="large-text" type="text" name="role_scopes[<?php echo esc_attr($slug); ?>]" value="<?php echo esc_attr($role_scopes[$slug]??''); ?>"></td></tr><?php } ?></tbody></table>
<h2>Individuelle Benutzer-Scopes</h2><p class="description">Benutzer und Rollen sind additiv. Benutzer kann als ID oder E-Mail angegeben werden.</p><table class="widefat striped" id="ath-user-scopes"><thead><tr><th>Benutzer-ID / E-Mail</th><th>Scopes</th><th></th></tr></thead><tbody><?php foreach($user_scopes as $uid=>$scope){$u=get_user_by('id',(int)$uid);self::user_scope_row($u?$u->user_email:$uid,$scope);} ?></tbody></table><p><button type="button" class="button" id="ath-add-user-scope">Benutzerregel hinzufügen</button></p>
<p class="submit"><button class="button button-primary">OAuthServer speichern</button></p></form></div>
<script>
(function(){function row(table,html){var tr=document.createElement('tr');tr.innerHTML=html;table.querySelector('tbody').appendChild(tr);}document.getElementById('ath-add-server-client').onclick=function(){row(document.getElementById('ath-server-clients'),'<td><input name="client_title[]"></td><td><input name="client_id[]"></td><td><input name="client_secret[]" type="password"></td><td><input class="large-text" name="client_redirect[]"></td><td><button type="button" class="button-link-delete" onclick="this.closest(\'tr\').remove()">Entfernen</button></td>');};document.getElementById('ath-add-user-scope').onclick=function(){row(document.getElementById('ath-user-scopes'),'<td><input name="scope_user[]"></td><td><input class="large-text" name="scope_user_scopes[]"></td><td><button type="button" class="button-link-delete" onclick="this.closest(\'tr\').remove()">Entfernen</button></td>');};})();
</script><?php }
    private static function client_row($c){?><tr><td><input name="client_title[]" value="<?php echo esc_attr($c['title']??''); ?>"></td><td><input name="client_id[]" value="<?php echo esc_attr($c['client_id']??''); ?>"></td><td><input name="client_secret[]" type="password" value="<?php echo esc_attr($c['client_secret']??''); ?>"></td><td><input class="large-text" name="client_redirect[]" value="<?php echo esc_attr($c['redirect_uri']??''); ?>"></td><td><button type="button" class="button-link-delete" onclick="this.closest('tr').remove()">Entfernen</button></td></tr><?php }
    private static function user_scope_row($user,$scope){?><tr><td><input name="scope_user[]" value="<?php echo esc_attr($user); ?>"></td><td><input class="large-text" name="scope_user_scopes[]" value="<?php echo esc_attr($scope); ?>"></td><td><button type="button" class="button-link-delete" onclick="this.closest('tr').remove()">Entfernen</button></td></tr><?php }
}
