<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_OAuth_Flow {
    public static function register_hooks(){add_action('admin_post_kornsw_ath_oauth_start',array(__CLASS__,'handle_start'));add_action('admin_post_nopriv_kornsw_ath_oauth_start',array(__CLASS__,'handle_start'));add_action('admin_post_kornsw_ath_oauth_callback',array(__CLASS__,'handle_callback'));add_action('admin_post_nopriv_kornsw_ath_oauth_callback',array(__CLASS__,'handle_callback'));add_action('admin_post_nopriv_kornsw_ath_link_existing',array(__CLASS__,'handle_link_existing'));add_action('admin_post_kornsw_ath_link_existing',array(__CLASS__,'handle_link_existing'));}
    public static function callback_url(){return admin_url('admin-post.php?action=kornsw_ath_oauth_callback');}
    public static function start($source_uid,$return_url,$purpose='api',$payload=array()){$profile=KornSW_ATH_Config_Repository::get_profile($source_uid);if(!$profile)wp_die('Unbekannte Token Source.',403);if(isset($profile['Enabled'])&&!$profile['Enabled'])wp_die('Token Source ist deaktiviert.',403);$issue_mode=(string)(($profile['AuthTokenConfig']??array())['IssueMode']??'');if(!str_starts_with($issue_mode,'OAUTH_'))wp_die('Diese Token Source verwendet keinen interaktiven OAuth-Issuing-Flow.',400);if(!get_current_user_id() && !KornSW_ATH_Config_Repository::is_login_source($source_uid))wp_die('Nicht angemeldete Benutzer dürfen nur eine als WordPress-Login qualifizierte Token Source verwenden.',403);$provider=KornSW_ATH_Provider_Registry::get_for_profile($profile);if(is_wp_error($provider))wp_die(esc_html($provider->get_error_message()),500);$user_id=get_current_user_id();$c=KornSW_ATH_Storage::create_continuation($source_uid,$user_id,$purpose,self::sanitize_return_url($return_url),$payload);if(is_wp_error($c))wp_die(esc_html($c->get_error_message()),500);$url=$provider->get_authorization_url($profile,self::callback_url(),$c['state'],$c['verifier']);if(is_wp_error($url))wp_die(esc_html($url->get_error_message()),500);wp_redirect($url,302);exit;}
    public static function handle_start(){$source=sanitize_text_field(wp_unslash($_GET['source']??''));$return=esc_url_raw(wp_unslash($_GET['return']??self::current_url()));$purpose=sanitize_key(wp_unslash($_GET['purpose']??'api'));self::start($source,$return,$purpose);}
    public static function handle_callback(){$state=sanitize_text_field(wp_unslash($_GET['state']??''));$code=sanitize_text_field(wp_unslash($_GET['code']??''));if($state===''||$code==='')wp_die('OAuth-Callback enthält keinen gültigen state/code.',400);$c=KornSW_ATH_Storage::consume_continuation_by_state($state);if(is_wp_error($c))wp_die(esc_html($c->get_error_message()),400);$profile=KornSW_ATH_Config_Repository::get_profile($c['source_uid']);if(!$profile)wp_die('Token Source existiert nicht mehr.',400);$provider=KornSW_ATH_Provider_Registry::get_for_profile($profile);if(is_wp_error($provider))wp_die(esc_html($provider->get_error_message()),500);$token=$provider->exchange_authorization_code($profile,$code,self::callback_url(),$c['verifier']);if(is_wp_error($token))wp_die(esc_html($token->get_error_message()),502);$identity=$provider->resolve_identity($profile,$token['access_token'],$token['id_token']??'');if(is_wp_error($identity))wp_die(esc_html($identity->get_error_message()),502);
        $user_id=(int)$c['user_id'];
        if($user_id>0){if($c['session_hash']!=='' && !hash_equals($c['session_hash'],KornSW_ATH_Storage::session_hash()))wp_die('WordPress-Sitzung hat sich während OAuth geändert.',403);$existing_subject=KornSW_ATH_Storage::get_connection_by_subject($c['source_uid'],$identity['subject']);if($existing_subject && (int)$existing_subject['user_id']!==$user_id)wp_die('Diese externe Identität ist bereits mit einem anderen WordPress-Benutzer verbunden.',409);KornSW_ATH_Storage::upsert_connection($user_id,$c['source_uid'],$identity);self::store_final_token($user_id,$c['source_uid'],$token,$identity,$c['purpose']);wp_safe_redirect($c['return_url']);exit;}
        self::complete_direct_login($c,$token,$identity);
    }
    private static function complete_direct_login($c,$token,$identity){$connection=KornSW_ATH_Storage::get_connection_by_subject($c['source_uid'],$identity['subject']);if($connection){$user_id=(int)$connection['user_id'];self::login_user($user_id);KornSW_ATH_Storage::upsert_connection($user_id,$c['source_uid'],$identity);KornSW_ATH_Storage::save_token_set($user_id,$c['source_uid'],'session',KornSW_ATH_Storage::session_hash(),$token,$identity['claims']);KornSW_ATH_Storage::set_binding($user_id,$c['source_uid'],false);wp_safe_redirect($c['return_url']);exit;}
        $email=sanitize_email($identity['email']??'');if($email==='')wp_die('Diese Login-Quelle liefert keine nutzbare E-Mail-Adresse. Ein WordPress-Konto kann deshalb weder sicher zugeordnet noch provisioniert werden.',409);$identity['email']=$email;$existing=get_user_by('email',$email);if($existing){self::render_link_existing($existing,$c,$token,$identity);exit;}$identity=self::require_new_user_identity($identity);if(is_wp_error($identity))wp_die(esc_html($identity->get_error_message()),409);
        $base=sanitize_user(strstr($email,'@',true),true);if($base==='')$base='oauthuser';$login=$base;$n=1;while(username_exists($login)){$login=$base.$n;$n++;}$user_id=wp_insert_user(array('user_login'=>$login,'user_pass'=>wp_generate_password(32,true,true),'user_email'=>$email,'display_name'=>$identity['display_name']?:$email,'first_name'=>$identity['given_name']??'','last_name'=>$identity['family_name']??'','role'=>KornSW_ATH_Config_Repository::get_auto_provision_role()));if(is_wp_error($user_id))wp_die(esc_html($user_id->get_error_message()),500);KornSW_ATH_Storage::upsert_connection($user_id,$c['source_uid'],$identity);self::login_user($user_id);KornSW_ATH_Storage::save_token_set($user_id,$c['source_uid'],'session',KornSW_ATH_Storage::session_hash(),$token,$identity['claims']);KornSW_ATH_Storage::set_binding($user_id,$c['source_uid'],false);do_action('kornsw_authtokenhandling_user_auto_provisioned',$user_id,$c['source_uid'],$identity);wp_safe_redirect($c['return_url']);exit;}

    private static function require_new_user_identity($identity){
        $email=sanitize_email($identity['email']??'');
        $given=trim((string)($identity['given_name']??''));
        $family=trim((string)($identity['family_name']??''));
        if($email==='')return new WP_Error('provisioning_email_missing','Diese Login-Quelle liefert keine nutzbare E-Mail-Adresse. Ein neuer WordPress-Benutzer kann deshalb nicht provisioniert werden.');
        if($given===''||$family==='')return new WP_Error('provisioning_name_missing','Diese Login-Quelle liefert für das Erstprovisioning nicht sowohl Vorname als auch Nachname. Ein neuer WordPress-Benutzer wird ohne diese Identitätsdaten nicht angelegt.');
        $identity['email']=$email;$identity['given_name']=$given;$identity['family_name']=$family;
        if(trim((string)($identity['display_name']??''))==='')$identity['display_name']=trim($given.' '.$family);
        return $identity;
    }
    private static function render_link_existing($user,$c,$token,$identity){$pending=wp_generate_uuid4();set_transient('kornsw_ath_link_'.$pending,array('user_id'=>$user->ID,'source_uid'=>$c['source_uid'],'return_url'=>$c['return_url'],'token'=>self::protect_token_result($token),'identity'=>$identity),10*MINUTE_IN_SECONDS);?><!doctype html><html><head><meta charset="utf-8"><title>WordPress-Konto bestätigen</title><?php wp_admin_css('login',true); ?></head><body class="login"><div id="login"><h1><a href="<?php echo esc_url(home_url('/')); ?>">WordPress</a></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><h2>Bestehendes Konto bestätigen</h2><p>Die externe E-Mail gehört bereits zu einem WordPress-Konto. Bitte bestätige einmalig dessen Passwort, um die Token Source sicher zu verknüpfen.</p><input type="hidden" name="action" value="kornsw_ath_link_existing"><input type="hidden" name="pending" value="<?php echo esc_attr($pending); ?>"><?php wp_nonce_field('kornsw_ath_link_'.$pending); ?><p><label>WordPress-Passwort<br><input class="input" type="password" name="password" required></label></p><p class="submit"><button class="button button-primary button-large">Konto verknüpfen</button></p></form></div></body></html><?php }
    public static function handle_link_existing(){$pending=sanitize_text_field(wp_unslash($_POST['pending']??''));check_admin_referer('kornsw_ath_link_'.$pending);$data=get_transient('kornsw_ath_link_'.$pending);if(!$data)wp_die('Verknüpfungsanforderung ist abgelaufen.',400);$user=get_user_by('id',(int)$data['user_id']);$password=(string)wp_unslash($_POST['password']??'');if(!$user||!wp_check_password($password,$user->user_pass,$user->ID))wp_die('Passwort ist nicht korrekt.',403);delete_transient('kornsw_ath_link_'.$pending);KornSW_ATH_Storage::upsert_connection($user->ID,$data['source_uid'],$data['identity']);self::login_user($user->ID);$token=self::unprotect_token_result($data['token']);if(is_wp_error($token))wp_die(esc_html($token->get_error_message()),500);KornSW_ATH_Storage::save_token_set($user->ID,$data['source_uid'],'session',KornSW_ATH_Storage::session_hash(),$token,$data['identity']['claims']);KornSW_ATH_Storage::set_binding($user->ID,$data['source_uid'],false);wp_safe_redirect($data['return_url']);exit;}
    private static function login_user($user_id){$expiration=time()+14*DAY_IN_SECONDS;$session_token=WP_Session_Tokens::get_instance($user_id)->create($expiration);wp_set_current_user($user_id);wp_set_auth_cookie($user_id,true,is_ssl(),$session_token);$_COOKIE[LOGGED_IN_COOKIE]=wp_generate_auth_cookie($user_id,$expiration,'logged_in',$session_token);$user=get_userdata($user_id);do_action('wp_login',$user->user_login,$user);}
    private static function protect_token_result($token){$copy=$token;foreach(array('access_token','refresh_token','id_token') as $f){if(isset($copy[$f])&&$copy[$f]!==''){$e=KornSW_ATH_Crypto::encrypt($copy[$f]);if(is_wp_error($e))return array('error'=>$e->get_error_message());$copy[$f]=$e;}}return $copy;}
    private static function unprotect_token_result($token){if(isset($token['error']))return new WP_Error('pending_token_error',$token['error']);$copy=$token;foreach(array('access_token','refresh_token','id_token') as $f){if(isset($copy[$f])&&$copy[$f]!==''){$d=KornSW_ATH_Crypto::decrypt($copy[$f]);if(is_wp_error($d))return $d;$copy[$f]=$d;}}return $copy;}
    private static function store_final_token($user_id,$source_uid,$token,$identity,$purpose){$is_login=$purpose==='login'||$purpose==='primary';$scope=$is_login?'session':'persistent';$sh=$scope==='session'?KornSW_ATH_Storage::session_hash():'';KornSW_ATH_Storage::save_token_set($user_id,$source_uid,$scope,$sh,$token,$identity['claims']);if($is_login)KornSW_ATH_Storage::set_binding($user_id,$source_uid,false);do_action('kornsw_authtokenhandling_connection_changed',$source_uid,$user_id,'connected');}
    public static function is_interactive_request(){return !wp_doing_cron() && !wp_doing_ajax() && !(defined('REST_REQUEST')&&REST_REQUEST) && php_sapi_name()!=='cli';}
    public static function current_url(){$scheme=is_ssl()?'https':'http';$host=$_SERVER['HTTP_HOST']??wp_parse_url(home_url(),PHP_URL_HOST);$uri=$_SERVER['REQUEST_URI']??'/';return esc_url_raw($scheme.'://'.$host.$uri);}
    private static function sanitize_return_url($url){$url=wp_validate_redirect($url,home_url('/'));return $url ?: home_url('/');}
}
