<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_GitHub_Provider extends KornSW_ATH_Provider_Base {
    public function invariant_name(){return 'github';} public function display_title(){return 'GitHub';}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){$args=array('client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'state'=>$state,'code_challenge'=>$this->pkce_challenge($verifier),'code_challenge_method'=>'S256');$scope=trim((string)$this->config($profile,'scopes','read:user user:email'));if(!empty($profile['LoginEnabled'])){$parts=preg_split('/\s+/', $scope, -1, PREG_SPLIT_NO_EMPTY);foreach(array('read:user','user:email') as $required){if(!in_array($required,$parts,true))$parts[]=$required;}$scope=implode(' ',$parts);}if($scope!=='')$args['scope']=$scope;return add_query_arg($args,'https://github.com/login/oauth/authorize');}
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$body=array('client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret',''),'code'=>$code,'redirect_uri'=>$redirect_uri,'code_verifier'=>$verifier);return $this->normalize_token_result($this->post_form('https://github.com/login/oauth/access_token',$body,array('Accept'=>'application/json')));}
    public function refresh_access_token($profile,$refresh_token){$body=array('client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret',''),'grant_type'=>'refresh_token','refresh_token'=>$refresh_token);return $this->normalize_token_result($this->post_form('https://github.com/login/oauth/access_token',$body,array('Accept'=>'application/json')));}
    public function validate_token($profile,$access_token){$cached=$this->validation_cache_get($profile,$access_token);if($cached!==false)return $cached;$data=$this->github_get('https://api.github.com/user',$access_token);if(is_wp_error($data)){$error_data=$data->get_error_data();$code=(int)(is_array($error_data)?($error_data['status']??0):0);if($code===401){$r=array('technical_success'=>true,'active'=>false,'reason'=>'GitHub token rejected','claims'=>array());$this->validation_cache_set($profile,$access_token,$r);return $r;}return array('technical_success'=>false,'active'=>false,'reason'=>$data->get_error_message(),'claims'=>array());}$r=array('technical_success'=>true,'active'=>!empty($data['id']),'valid_until'=>null,'reason'=>null,'claims'=>$data);$this->validation_cache_set($profile,$access_token,$r);return $r;}
    public function resolve_identity($profile,$access_token,$id_token=''){$data=$this->github_get('https://api.github.com/user',$access_token);if(is_wp_error($data))return $data;$email=(string)($data['email']??'');if($email===''){$emails=$this->github_get('https://api.github.com/user/emails',$access_token);if(!is_wp_error($emails)&&is_array($emails)){foreach($emails as $e){if(!empty($e['primary'])&&!empty($e['verified'])){$email=(string)$e['email'];break;}}}}$id=(string)($data['id']??'');if($id==='')return new WP_Error('missing_subject','GitHub liefert keine User-ID.');$display=trim((string)($data['name']??''));$given='';$family='';if($display!==''){$parts=preg_split('/\s+/', $display, 2);$given=(string)($parts[0]??'');$family=(string)($parts[1]??'');}return array('subject'=>$id,'email'=>$email,'given_name'=>$given,'family_name'=>$family,'display_name'=>$display!==''?$display:(string)($data['login']??''),'claims'=>$data);}
    private function github_get($url,$token){$response=wp_remote_get($url,array('timeout'=>20,'headers'=>array('Authorization'=>'Bearer '.$token,'Accept'=>'application/vnd.github+json','X-GitHub-Api-Version'=>'2022-11-28','User-Agent'=>'KornSW-AuthTokenHandling')));if(is_wp_error($response))return $response;$code=(int)wp_remote_retrieve_response_code($response);$body=json_decode((string)wp_remote_retrieve_body($response),true);if($code<200||$code>=300)return new WP_Error('github_http_'.$code,'GitHub API antwortete mit HTTP '.$code,array('status'=>$code));return is_array($body)?$body:new WP_Error('github_invalid_response','Ungültige GitHub-Antwort.');}
    public function has_capability($profile,$name){if($name==='refresh_token')return !empty(($profile['ProviderConfiguration']??array())['supports_refresh_token']);return in_array($name,array('pkce','authorization_code','userinfo','introspection'),true);}
}
