<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Remote_WordPress_Provider extends KornSW_ATH_Provider_Base {
    public function invariant_name(){return 'remote_wordpress';}
    public function display_title(){return 'Remote-WordPress (AuthTokenHandling)';}
    private function endpoint($profile,$action){$base=rtrim((string)$this->config($profile,'remote_base_url',''),'/');if($base==='')return '';return $base.'/wp-admin/admin-post.php?action='.rawurlencode($action);}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){$url=$this->endpoint($profile,'kornsw_ath_server_authorize');if($url==='')return new WP_Error('remote_base_missing','Remote WordPress Base URL fehlt.');return add_query_arg(array('response_type'=>'code','client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'state'=>$state,'scope'=>(string)$this->config($profile,'scopes',''),'code_challenge'=>$this->pkce_challenge($verifier),'code_challenge_method'=>'S256'),$url);}
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$url=$this->endpoint($profile,'kornsw_ath_server_token');if($url==='')return new WP_Error('remote_base_missing','Remote WordPress Base URL fehlt.');return $this->normalize_token_result($this->post_form($url,array('grant_type'=>'authorization_code','client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret',''),'code'=>$code,'redirect_uri'=>$redirect_uri,'code_verifier'=>$verifier),array('Accept'=>'application/json')));}
    public function refresh_access_token($profile,$refresh_token){$url=$this->endpoint($profile,'kornsw_ath_server_token');return $this->normalize_token_result($this->post_form($url,array('grant_type'=>'refresh_token','client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret',''),'refresh_token'=>$refresh_token),array('Accept'=>'application/json')));}
    public function validate_token($profile,$access_token){$url=$this->endpoint($profile,'kornsw_ath_server_introspect');$data=$this->post_form($url,array('token'=>$access_token,'client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret','')),array('Accept'=>'application/json'));if(is_wp_error($data))return array('technical_success'=>false,'active'=>false,'reason'=>$data->get_error_message(),'claims'=>array());$active=!empty($data['active']);return array('technical_success'=>true,'active'=>$active,'valid_until'=>isset($data['exp'])?(int)$data['exp']:null,'reason'=>$active?null:(string)($data['error_description']??'inactive'),'claims'=>$data);}
    public function resolve_identity($profile,$access_token,$id_token=''){$v=$this->validate_token($profile,$access_token);if(empty($v['technical_success'])||empty($v['active']))return new WP_Error('remote_identity_failed',$v['reason']??'Remote Introspection fehlgeschlagen.');$c=$v['claims'];$sub=(string)($c['sub']??'');if($sub==='')return new WP_Error('missing_subject','Remote WordPress Introspection enthält kein sub.');return array('subject'=>$sub,'email'=>(string)($c['email']??$sub),'given_name'=>(string)($c['given_name']??''),'family_name'=>(string)($c['family_name']??''),'display_name'=>(string)($c['name']??''),'claims'=>$c);}
    public function has_capability($profile,$name){return in_array($name,array('authorization_code','pkce','refresh_token','id_token','introspection','userinfo'),true);}
}
