<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Microsoft_Provider extends KornSW_ATH_Provider_Base {
    public function invariant_name(){return 'microsoft';}
    public function display_title(){return 'Microsoft';}
    private function tenant($profile){$tenant=trim((string)$this->config($profile,'tenant','common'));return $tenant!==''?$tenant:'common';}
    private function base($profile){return 'https://login.microsoftonline.com/'.rawurlencode($this->tenant($profile)).'/oauth2/v2.0';}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){$scope=trim((string)$this->config($profile,'scopes','openid profile email offline_access'));$p=preg_split('/\s+/', $scope,-1,PREG_SPLIT_NO_EMPTY);foreach(array('openid','profile','email','offline_access') as $r){if(!in_array($r,$p,true))$p[]=$r;}$scope=implode(' ',$p);return add_query_arg(array('client_id'=>$this->auth_config($profile,'ClientId',''),'response_type'=>'code','redirect_uri'=>$redirect_uri,'response_mode'=>'query','scope'=>$scope,'state'=>$state,'code_challenge'=>$this->pkce_challenge($verifier),'code_challenge_method'=>'S256'),$this->base($profile).'/authorize');}
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$body=array('client_id'=>$this->auth_config($profile,'ClientId',''),'grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>$redirect_uri,'code_verifier'=>$verifier);$secret=(string)$this->auth_config($profile,'ClientSecret','');if($secret!=='')$body['client_secret']=$secret;return $this->normalize_token_result($this->post_form($this->base($profile).'/token',$body,array('Accept'=>'application/json')));}
    public function refresh_access_token($profile,$refresh_token){$body=array('client_id'=>$this->auth_config($profile,'ClientId',''),'grant_type'=>'refresh_token','refresh_token'=>$refresh_token,'scope'=>(string)$this->config($profile,'scopes','openid profile email offline_access'));$secret=(string)$this->auth_config($profile,'ClientSecret','');if($secret!=='')$body['client_secret']=$secret;return $this->normalize_token_result($this->post_form($this->base($profile).'/token',$body,array('Accept'=>'application/json')));}
    public function validate_token($profile,$access_token){$data=$this->get_json('https://graph.microsoft.com/oidc/userinfo',array('Authorization'=>'Bearer '.$access_token,'Accept'=>'application/json'));if(is_wp_error($data))return array('technical_success'=>false,'active'=>false,'reason'=>$data->get_error_message(),'claims'=>array());return array('technical_success'=>true,'active'=>!empty($data['sub']),'valid_until'=>null,'reason'=>empty($data['sub'])?'missing sub':null,'claims'=>$data);}
    public function resolve_identity($profile,$access_token,$id_token=''){$data=$this->get_json('https://graph.microsoft.com/oidc/userinfo',array('Authorization'=>'Bearer '.$access_token,'Accept'=>'application/json'));if(is_wp_error($data))return $data;$sub=(string)($data['sub']??'');if($sub==='')return new WP_Error('missing_subject','Microsoft UserInfo enthält kein sub.');return array('subject'=>$sub,'email'=>(string)($data['email']??$data['preferred_username']??''),'given_name'=>(string)($data['given_name']??''),'family_name'=>(string)($data['family_name']??''),'display_name'=>(string)($data['name']??''),'claims'=>$data);}
    public function has_capability($profile,$name){return in_array($name,array('refresh_token','id_token','pkce','authorization_code','userinfo','introspection'),true);}
}
