<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Apple_Provider extends KornSW_ATH_Provider_Base {
    public function invariant_name(){return 'apple';}
    public function display_title(){return 'Apple';}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){$scope=trim((string)$this->config($profile,'scopes','name email'));return add_query_arg(array('client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'response_type'=>'code id_token','response_mode'=>'form_post','scope'=>$scope,'state'=>$state),'https://appleid.apple.com/auth/authorize');}
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$secret=$this->client_secret($profile);if(is_wp_error($secret))return $secret;$body=array('client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$secret,'code'=>$code,'grant_type'=>'authorization_code','redirect_uri'=>$redirect_uri);return $this->normalize_token_result($this->post_form('https://appleid.apple.com/auth/token',$body,array('Accept'=>'application/json')));}
    public function refresh_access_token($profile,$refresh_token){$secret=$this->client_secret($profile);if(is_wp_error($secret))return $secret;return $this->normalize_token_result($this->post_form('https://appleid.apple.com/auth/token',array('client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$secret,'grant_type'=>'refresh_token','refresh_token'=>$refresh_token),array('Accept'=>'application/json')));}
    public function validate_token($profile,$access_token){return array('technical_success'=>false,'active'=>false,'reason'=>'Apple bietet für Access Tokens keinen RFC7662-Introspection-Endpunkt. Verwende IMPLICIT_WHEN_USED mit Ablauf/Refresh.','claims'=>array());}
    public function resolve_identity($profile,$access_token,$id_token=''){if($id_token==='')return new WP_Error('apple_id_token_missing','Apple hat kein ID Token geliefert.');$claims=KornSW_ATH_JWT_Helper::verify_rs256_jwks($id_token,'https://appleid.apple.com/auth/keys','https://appleid.apple.com',(string)$this->auth_config($profile,'ClientId',''));if(is_wp_error($claims))return $claims;$sub=(string)($claims['sub']??'');if($sub==='')return new WP_Error('missing_subject','Apple ID Token enthält kein sub.');return array('subject'=>$sub,'email'=>(string)($claims['email']??''),'given_name'=>'','family_name'=>'','display_name'=>'','claims'=>$claims);}
    public function has_capability($profile,$name){return in_array($name,array('authorization_code','refresh_token','id_token'),true);}
    private function client_secret($profile){$team=trim((string)$this->config($profile,'apple_team_id',''));$kid=trim((string)$this->config($profile,'apple_key_id',''));$key=(string)$this->config($profile,'apple_private_key','');$client=(string)$this->auth_config($profile,'ClientId','');if($team===''||$kid===''||$key===''||$client==='')return new WP_Error('apple_config_missing','Apple benötigt Services ID (ClientId), Team ID, Key ID und Private Key.');$now=time();return KornSW_ATH_JWT_Helper::encode_es256(array('iss'=>$team,'iat'=>$now,'exp'=>$now+15552000,'aud'=>'https://appleid.apple.com','sub'=>$client),$key,$kid);}
}
