<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Google_Provider extends KornSW_ATH_Provider_Base {
    public function invariant_name(){return 'google';} public function display_title(){return 'Google';}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){
        $scope=trim((string)$this->config($profile,'scopes','openid email profile'));if(!empty($profile['LoginEnabled'])){$parts=preg_split('/\s+/', $scope, -1, PREG_SPLIT_NO_EMPTY);foreach(array('openid','email','profile') as $required){if(!in_array($required,$parts,true))$parts[]=$required;}$scope=implode(' ',$parts);}$args=array('response_type'=>'code','client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'scope'=>$scope,'state'=>$state,'code_challenge'=>$this->pkce_challenge($verifier),'code_challenge_method'=>'S256','include_granted_scopes'=>'true','access_type'=>'offline','prompt'=>'consent');
        return add_query_arg($args,'https://accounts.google.com/o/oauth2/v2/auth');
    }
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$body=array('grant_type'=>'authorization_code','code'=>$code,'client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'code_verifier'=>$verifier);$secret=(string)$this->auth_config($profile,'ClientSecret','');if($secret!=='')$body['client_secret']=$secret;return $this->normalize_token_result($this->post_form('https://oauth2.googleapis.com/token',$body,array('Accept'=>'application/json')));}
    public function refresh_access_token($profile,$refresh_token){$body=array('grant_type'=>'refresh_token','refresh_token'=>$refresh_token,'client_id'=>$this->auth_config($profile,'ClientId',''));$secret=(string)$this->auth_config($profile,'ClientSecret','');if($secret!=='')$body['client_secret']=$secret;return $this->normalize_token_result($this->post_form('https://oauth2.googleapis.com/token',$body,array('Accept'=>'application/json')));}
    public function validate_token($profile,$access_token){$cached=$this->validation_cache_get($profile,$access_token);if($cached!==false)return $cached;$data=$this->get_json(add_query_arg('access_token',$access_token,'https://oauth2.googleapis.com/tokeninfo'),array('Accept'=>'application/json'));if(is_wp_error($data))return array('technical_success'=>false,'active'=>false,'reason'=>$data->get_error_message(),'claims'=>array());$active=isset($data['expires_in'])&&(int)$data['expires_in']>0;$result=array('technical_success'=>true,'active'=>$active,'valid_until'=>$active?time()+(int)$data['expires_in']:null,'reason'=>$active?null:'expired','claims'=>$data);$this->validation_cache_set($profile,$access_token,$result);return $result;}
    public function resolve_identity($profile,$access_token,$id_token=''){$data=$this->get_json('https://openidconnect.googleapis.com/v1/userinfo',array('Authorization'=>'Bearer '.$access_token,'Accept'=>'application/json'));if(is_wp_error($data))return $data;$sub=(string)($data['sub']??'');if($sub==='')return new WP_Error('missing_subject','Google UserInfo enthält kein sub.');return array('subject'=>$sub,'email'=>(string)($data['email']??''),'given_name'=>(string)($data['given_name']??''),'family_name'=>(string)($data['family_name']??''),'display_name'=>(string)($data['name']??''),'claims'=>$data);}
    public function has_capability($profile,$name){return in_array($name,array('introspection','refresh_token','id_token','pkce','authorization_code','userinfo'),true);}
}
