<?php
if (!defined('ABSPATH')) { exit; }
final class KornSW_ATH_Facebook_Provider extends KornSW_ATH_Provider_Base {
    const API_VERSION='v26.0';
    public function invariant_name(){return 'facebook';}
    public function display_title(){return 'Facebook';}
    public function get_authorization_url($profile,$redirect_uri,$state,$verifier){$scope=trim((string)$this->config($profile,'scopes','email public_profile'));return add_query_arg(array('client_id'=>$this->auth_config($profile,'ClientId',''),'redirect_uri'=>$redirect_uri,'state'=>$state,'response_type'=>'code','scope'=>$scope),'https://www.facebook.com/'.self::API_VERSION.'/dialog/oauth');}
    public function exchange_authorization_code($profile,$code,$redirect_uri,$verifier){$url='https://graph.facebook.com/'.self::API_VERSION.'/oauth/access_token';$data=$this->get_json(add_query_arg(array('client_id'=>$this->auth_config($profile,'ClientId',''),'client_secret'=>$this->auth_config($profile,'ClientSecret',''),'redirect_uri'=>$redirect_uri,'code'=>$code),$url),array('Accept'=>'application/json'));return $this->normalize_token_result($data);}
    public function refresh_access_token($profile,$refresh_token){return new WP_Error('refresh_unsupported','Facebook Login liefert in diesem Provider keinen OAuth Refresh Token.');}
    public function validate_token($profile,$access_token){$app=(string)$this->auth_config($profile,'ClientId','').'|'.(string)$this->auth_config($profile,'ClientSecret','');$url=add_query_arg(array('input_token'=>$access_token,'access_token'=>$app),'https://graph.facebook.com/'.self::API_VERSION.'/debug_token');$data=$this->get_json($url,array('Accept'=>'application/json'));if(is_wp_error($data))return array('technical_success'=>false,'active'=>false,'reason'=>$data->get_error_message(),'claims'=>array());$d=$data['data']??array();$active=!empty($d['is_valid']);return array('technical_success'=>true,'active'=>$active,'valid_until'=>isset($d['expires_at'])?(int)$d['expires_at']:null,'reason'=>$active?null:'inactive','claims'=>$d);}
    public function resolve_identity($profile,$access_token,$id_token=''){$url=add_query_arg(array('fields'=>'id,name,email,first_name,last_name','access_token'=>$access_token),'https://graph.facebook.com/'.self::API_VERSION.'/me');$data=$this->get_json($url,array('Accept'=>'application/json'));if(is_wp_error($data))return $data;$id=(string)($data['id']??'');if($id==='')return new WP_Error('missing_subject','Facebook liefert keine User-ID.');return array('subject'=>$id,'email'=>(string)($data['email']??''),'given_name'=>(string)($data['first_name']??''),'family_name'=>(string)($data['last_name']??''),'display_name'=>(string)($data['name']??''),'claims'=>$data);}
    public function has_capability($profile,$name){return in_array($name,array('authorization_code','userinfo','introspection'),true);}
}
